apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashview-agent
  labels:
    app: hashview-agent
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hashview-agent
  template:
    metadata:
      labels:
        app: hashview-agent
    spec:
      containers:
      - name: hashview-agent
        image: yourusername/hashview-agent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.8"
            memory: "4096Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        env:
        - name: HASHVIEW_SERVER_URL
          value: "https://hash.domainhere.com"
        - name: HASHVIEW_SERVER_TOKEN
          value: "TOKENHERE" 
